name: DigitalOcean CICD

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions: {}

env:
    USER: cee
    APP_PATH: /home/cee/app/fiskebot/
    HOST: ${{ secrets.DEPLOY_IP }}
    SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Configure SSH on github runner
              run: |
                pwd
                ls -la
                mkdir "~/.ssh/"
                echo "$SSH_KEY" > "~/.ssh/private.pem"
                chmod 600 "~/.ssh/private.pem"
                printf "Host docean\n  HostName $HOST\n  User $USER\n  IdentityFile ~/.ssh/private.pem\n  StrictHostKeyChecking no\n" > "$RUNNER_HOME/.ssh/config"
            - name: Build docker image
              run: |
                docker build -t steinsiv/fiskebot:latest .
                docker save steinsiv/fiskebot:latest | gzip > steinsiv_fiskebot_latest.tar.gz
                ls -la
                pwd
            - name: Deploy docker compose and .env file
              run: |
                scp docker-compose.yml "docean:$APP_PATH/docker-compose.yml"
                scp steinsiv_fiskebot_latest.tar.gz "docean:$APP_PATH/steinsiv_fiskebot_latest.tar.gz"
                ssh docean "cd $APP_PATH && echo 'just a test, workflow was here' >> workflow.txt"
            - name: Cleanup SSH configs
              if: always()
              run: |
                rm -rf "$RUNNER_HOME/.ssh"
